name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ github.workspace }}/Qt
          key: ${{ runner.os }}-QtCache

      - uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache.outputs.cache-hit }}
          modules: core gui network test

      - run: |
          sudo apt-get install alsa alsa-tools libasound2-dev alsa-oss
        if: runner.os == 'Linux'

      - run: cmake -DCMAKE_INSTALL_PREFIX=dist -DQMIDI_BUILD_TESTS=ON -S . -B build

      - run: cmake --build build --config Release

      # Skipping tests here, unfortunately audio/midi stuff are not available on workers

      - run: cmake --install build

      - uses: actions/upload-artifact@v1
        with:
          name: release-${{ runner.os }}
          path: dist
