name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache.outputs.cache-hit }}
          modules: core gui network test

      - run: sudo apt-get install alsa alsa-tools libasound2-dev
        if: ${{ runner.os }} == 'Linux'

      - run: cmake -DCMAKE_INSTALL_PREFIX=dist -DQMIDI_BUILD_TESTS=ON -S . -B build

      - run: cmake --build build --config Release

      - run: ctest -C Release --output-on-failure
        working-directory: build

      - run: cmake --install build

      - uses: actions/upload-artifact@v1
        with:
          name: release-${{ runner.os }}
          path: dist
